version: '3.8'

services:
  # PostgreSQL Vector Database
  postgres:
    image: pgvector/pgvector:pg16
    container_name: superclaude-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=superclaude_rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecure
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d superclaude_rag"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG API with OpenAI
  superclaude-rag:
    build: 
      context: ../rag_api
      dockerfile: Dockerfile
    container_name: superclaude-rag-api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - VECTOR_DB_TYPE=pgvector
      - POSTGRES_DB=superclaude_rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecure
      - DB_HOST=postgres
      - DB_PORT=5432
      - COLLECTION_NAME=superclaude_vectors
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - EMBEDDINGS_MODEL=text-embedding-3-small
      - EMBEDDING_DIMENSIONS=1536
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - RAG_HOST=0.0.0.0
      - RAG_PORT=8000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: